# Generated by Django 4.2.5 on 2023-09-16 09:32

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("theBlog", "0003_blogpost_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
