# Generated by Django 4.2.5 on 2023-09-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theBlog", "0004_alter_blogpost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
