# Generated by Django 4.2.5 on 2023-09-16 14:15

from django.db import migrations, models
import theBlog.models


class Migration(migrations.Migration):
    dependencies = [
        ("theBlog", "0005_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="embedded_images",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=theBlog.models.get_upload_location_post_images,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=theBlog.models.get_upload_location_post_images,
            ),
        ),
    ]
